name: Update Script

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest script
        run: |
          curl -o main_1.lua https://raw.githubusercontent.com/YourUsername/YourRepo/main/raw/scripts/main_1.lua
      - name: Commit and push changes
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add main_1.lua
          git commit -m "Update main_1.lua"
          git push
